/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test4.ts" instead.
 */

#include <check.h>

#line 1 "test4.ts"
#include "buf.h"
#include <stdlib.h>

long *ai = 0;

START_TEST(test4)
{
#line 7
	buf_grow(ai, 1000);
    ck_assert_int_eq(buf_capacity(ai), 1000);

}
END_TEST

START_TEST(test41)
{
#line 11
	buf_grow(ai, 1000);
    ck_assert_int_eq(buf_size(ai), 0);

}
END_TEST

START_TEST(test42)
{
#line 15
	buf_grow(ai, 1000);
	buf_trunc(ai, 100);
    ck_assert_int_eq(buf_capacity(ai), 100);
    buf_free(ai);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test4);
    tcase_add_test(tc1_1, test41);
    tcase_add_test(tc1_1, test42);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
