/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test3.ts" instead.
 */

#include <check.h>

#line 1 "test3.ts"
#include "buf.h"
#include <stdlib.h>

long *ai = 0;

START_TEST(test3)
{
#line 7
	for (int i = 0; i < 10000; i++)
    	buf_push(ai, i);
    ck_assert_int_eq(buf_size(ai), 10000);

}
END_TEST

START_TEST(test31)
{
#line 12
	for (int i = 0; i < 10000; i++)
    	buf_push(ai, i);
    int match = 0;
    for (int i = 0; i < (int)(buf_size(ai)); i++)
        match += ai[i] == i;
    ck_assert_int_eq(match, 10000);
    buf_free(ai);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test3);
    tcase_add_test(tc1_1, test31);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
