/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test1.ts" instead.
 */

#include <check.h>

#line 1 "test1.ts"
#include "buf.h"
#include <stdlib.h>

float *a = 0;

START_TEST(test1)
{
#line 7
    ck_assert_int_eq(buf_capacity(a), 0);

}
END_TEST

START_TEST(test11)
{
#line 10
	ck_assert_int_eq(buf_size(a), 0);

}
END_TEST

START_TEST(test12)
{
#line 13
	buf_push(a, 1.3f);
	ck_assert_int_eq(buf_size(a), 1);

}
END_TEST

START_TEST(test13)
{
#line 17
	buf_push(a, 1.3f);
	ck_assert(a[0] == (float)1.3f);

}
END_TEST

START_TEST(test14)
{
#line 21
	buf_push(a, 1.3f);
	buf_clear(a);
	ck_assert_int_eq(buf_size(a), 0);

}
END_TEST

START_TEST(test15)
{
#line 26
	buf_push(a, 1.3f);
	buf_clear(a);
    ck_assert(a != 0);

}
END_TEST

START_TEST(test16)
{
#line 31
	buf_push(a, 1.3f);
	buf_clear(a);
	buf_free(a);
    ck_assert(a == 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test1);
    tcase_add_test(tc1_1, test11);
    tcase_add_test(tc1_1, test12);
    tcase_add_test(tc1_1, test13);
    tcase_add_test(tc1_1, test14);
    tcase_add_test(tc1_1, test15);
    tcase_add_test(tc1_1, test16);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
