/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test2.ts" instead.
 */

#include <check.h>

#line 1 "test2.ts"
#include "buf.h"
#include <stdlib.h>

float *a = 0;

START_TEST(test2)
{
#line 7
	buf_clear(a);
    ck_assert_int_eq(buf_size(a), 0);

}
END_TEST

START_TEST(test21)
{
#line 11
	buf_clear(a);
    ck_assert(a == 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test2);
    tcase_add_test(tc1_1, test21);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
