/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test5.ts" instead.
 */

#include <check.h>

#line 1 "test5.ts"
#include "buf.h"
#include <stdlib.h>

#define MAXLEN 64
float *a = 0;

START_TEST(test5)
{
#line 8
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    ck_assert_int_eq(buf_size(a), 4);

}
END_TEST

START_TEST(test51)
{
#line 15
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    ck_assert(buf_pop(a) == (float)1.4f);

}
END_TEST

START_TEST(test52)
{
#line 22
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    buf_pop(a);
    buf_trunc(a, 3);
    ck_assert_int_eq(buf_size(a), 3);

}
END_TEST

START_TEST(test53)
{
#line 31
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    buf_pop(a);
    buf_trunc(a, 3);
    ck_assert(buf_pop(a) == (float)1.3f);

}
END_TEST

START_TEST(test54)
{
#line 40
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    buf_pop(a);
    buf_trunc(a, 3);
    buf_pop(a);
    ck_assert(buf_pop(a) == (float)1.2f);

}
END_TEST

START_TEST(test55)
{
#line 50
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    buf_pop(a);
    buf_trunc(a, 3);
    buf_pop(a);
    buf_pop(a);
    ck_assert(buf_pop(a) == (float)1.1f);

}
END_TEST

START_TEST(test56)
{
#line 61
	buf_push(a, 1.1);
    buf_push(a, 1.2);
    buf_push(a, 1.3);
    buf_push(a, 1.4);
    buf_pop(a);
    buf_trunc(a, 3);
    buf_pop(a);
    buf_pop(a);
    buf_pop(a);
    ck_assert_int_eq(buf_size(a), 0); 
    buf_free(a);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test5);
    tcase_add_test(tc1_1, test51);
    tcase_add_test(tc1_1, test52);
    tcase_add_test(tc1_1, test53);
    tcase_add_test(tc1_1, test54);
    tcase_add_test(tc1_1, test55);
    tcase_add_test(tc1_1, test56);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
